version = "0.3.2"

[scripts]
    build.cmd  = "cargo build"
    build.desc = "builds the project"
    test.cmd   = "cargo watch -x \"test\""
    test.desc  = "runs automated tests for the project"
    dev.cmd    = ["cd src", "cargo run -- %%"]
    dev.desc   = "tests the project with the given arguments"
    check.cmd  = "cargo check && cargo fmt -- --check && cargo clippy && cargo test"
    check.desc = "validates the code (same checks as on CI)"

    release.cmd     = "standard-version --sign --commit-all && git push --follow-tags %% origin main"
    release.desc    = "increments the git version of the project and pushes it (update version throughout project first)"
    release-bx.cmd  = "standard-version --commit-all && git push --follow-tags %% origin main"
    release-bx.desc = "increments the git version of the project and pushes it (update version throughout project first)"

    publish.cmd  = "cargo publish %%"
    publish.desc = "publishes the binary to crates.io"
