name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
    build-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: cargo check && cargo fmt -- --check && cargo clippy && cargo test
